file:
  /etc/filebeat/filebeat.yml:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
    contains: []
  /var/ossec/bin/ossec-control:
    exists: true
    mode: "0750"
    owner: root
    group: root
    filetype: file
    contains: []
  /var/ossec/etc/lists/audit-keys:
    exists: true
    mode: "0660"
    owner: wazuh
    group: wazuh
    filetype: file
    contains: []
  /var/ossec/etc/manager.conf:
    exists: true
    mode: "0660"
    owner: root
    group: wazuh
    filetype: file
    contains: []
  /var/ossec/etc/rules/local_rules.xml:
    exists: true
    mode: "0660"
    owner: wazuh
    group: wazuh
    filetype: file
    contains: []
  /var/ossec/etc/sslmanager.cert:
    exists: true
    mode: "0640"
    owner: root
    group: root
    filetype: file
    contains: []
  /var/ossec/etc/sslmanager.key:
    exists: true
    mode: "0640"
    owner: root
    group: root
    filetype: file
    contains: []
package:
  filebeat:
    installed: true
    versions:
    - 7.10.0
  wazuh-manager:
    installed: true
    versions:
    - 5.0.0
port:
  tcp:1514:
    listening: true
    ip:
    - 0.0.0.0
  tcp:1515:
    listening: true
    ip:
    - 0.0.0.0
  tcp:55000:
    listening: true
    ip:
    - 0.0.0.0
user:
  wazuh:
    exists: true
    groups:
    - wazuh
    home: /var/ossec
    shell: /sbin/nologin
  wazuh:
    exists: true
    groups:
    - wazuh
    home: /var/ossec
    shell: /sbin/nologin
  wazuh:
    exists: true
    groups:
    - wazuh
    home: /var/ossec
    shell: /sbin/nologin
group:
  wazuh:
    exists: true
process:
  filebeat:
    running: true
  ossec-analysisd:
    running: true
  ossec-authd:
    running: true
  ossec-monitord:
    running: true
  ossec-remoted:
    running: true
  s6-supervise:
    running: true
  wazuh-db:
    running: true
  wazuh-modulesd:
    running: true
